-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-22 16:06:33 EET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE acces_right CASCADE CONSTRAINTS;

DROP TABLE attraction CASCADE CONSTRAINTS;

DROP TABLE attraction_type CASCADE CONSTRAINTS;

DROP TABLE "COMMENT" CASCADE CONSTRAINTS;

DROP TABLE location CASCADE CONSTRAINTS;

DROP TABLE "USER" CASCADE CONSTRAINTS;

DROP TABLE user_to_right CASCADE CONSTRAINTS;

CREATE TABLE acces_right (
    id_acces_right   NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    user_priority    NUMBER(3) NOT NULL
)
LOGGING;

ALTER TABLE acces_right ADD CONSTRAINT acces_right_pk PRIMARY KEY ( id_acces_right );

CREATE TABLE attraction (
    id_attraction            NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    name                     VARCHAR2(30) NOT NULL,
    description              VARCHAR2(60),
    open_time                DATE NOT NULL,
    close_time               DATE NOT NULL,
    create_attraction_time   DATE NOT NULL,
    image_path               VARCHAR2(30) NOT NULL,
    rating                   NUMBER(3) DEFAULT ON NULL 0,
    id_location              NUMBER(7) NOT NULL,
    id_attraction_type       NUMBER(7) NOT NULL,
    id_user                  NUMBER(7) NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX attraction__idx ON
    attraction (
        id_location
    ASC )
        LOGGING;

ALTER TABLE attraction ADD CONSTRAINT attraction_pk PRIMARY KEY ( id_attraction );

CREATE TABLE attraction_type (
    id_attraction_type   NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    title                VARCHAR2(30) NOT NULL,
    description          VARCHAR2(60),
    image_path           VARCHAR2(30) NOT NULL
)
LOGGING;

ALTER TABLE attraction_type ADD CONSTRAINT attraction_type_pk PRIMARY KEY ( id_attraction_type );

ALTER TABLE attraction_type ADD CONSTRAINT attraction_type_title_un UNIQUE ( title );

CREATE TABLE "COMMENT" (
    id_comment        NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    comment_content   VARCHAR2(50) NOT NULL,
    posting_date      DATE NOT NULL,
    id_user           NUMBER(7) NOT NULL,
    id_attraction     NUMBER(7) NOT NULL,
    rating            NUMBER(3) DEFAULT ON NULL 0
)
LOGGING;

ALTER TABLE "COMMENT" ADD CONSTRAINT comment_pk PRIMARY KEY ( id_comment );

CREATE TABLE location (
    id_location                NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    address                    VARCHAR2(40) NOT NULL,
    postal_code                VARCHAR2(20),
    attraction_id_attraction   NUMBER(7)
)
LOGGING;

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( id_location );

ALTER TABLE location ADD CONSTRAINT location_atr_un UNIQUE ( attraction_id_attraction );

CREATE TABLE "USER" (
    id_user      NUMBER(7)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    first_name   VARCHAR2(40) NOT NULL,
    last_name    VARCHAR2(30) NOT NULL,
    email        VARCHAR2(50) NOT NULL,
    password     VARCHAR2(30) NOT NULL
)
LOGGING;

ALTER TABLE "USER"
    ADD CONSTRAINT user_ck_email CHECK ( REGEXP_LIKE ( email,
                                                       '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE "USER"
    ADD CONSTRAINT user_ck_password CHECK ( length(password) >= 6 );

ALTER TABLE "USER" ADD CONSTRAINT user_pk PRIMARY KEY ( id_user );

ALTER TABLE "USER" ADD CONSTRAINT user_email_un UNIQUE ( email );

CREATE TABLE user_to_right (
    user_id_user                 NUMBER(7) NOT NULL,
    acces_right_id_acces_right   NUMBER(7) NOT NULL
)
LOGGING;

ALTER TABLE user_to_right ADD CONSTRAINT user_to_right_pk PRIMARY KEY ( user_id_user,
                                                                        acces_right_id_acces_right );

ALTER TABLE "COMMENT"
    ADD CONSTRAINT attr_to_comm FOREIGN KEY ( id_attraction )
        REFERENCES attraction ( id_attraction )
    NOT DEFERRABLE;

ALTER TABLE attraction
    ADD CONSTRAINT attr_to_loc FOREIGN KEY ( id_location )
        REFERENCES location ( id_location )
    NOT DEFERRABLE;

ALTER TABLE attraction
    ADD CONSTRAINT attr_to_type FOREIGN KEY ( id_attraction_type )
        REFERENCES attraction_type ( id_attraction_type )
    NOT DEFERRABLE;

ALTER TABLE attraction
    ADD CONSTRAINT user_to_attr FOREIGN KEY ( id_user )
        REFERENCES "USER" ( id_user )
    NOT DEFERRABLE;

ALTER TABLE "COMMENT"
    ADD CONSTRAINT user_to_comm FOREIGN KEY ( id_user )
        REFERENCES "USER" ( id_user )
    NOT DEFERRABLE;

ALTER TABLE user_to_right
    ADD CONSTRAINT user_to_right_acces_right_fk FOREIGN KEY ( acces_right_id_acces_right )
        REFERENCES acces_right ( id_acces_right )
    NOT DEFERRABLE;

ALTER TABLE user_to_right
    ADD CONSTRAINT user_to_right_user_fk FOREIGN KEY ( user_id_user )
        REFERENCES "USER" ( id_user )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
