// <auto-generated />
using System;
using IaSiViziteaza.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IaSiViziteaza.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190710100045_UserRightRelation")]
    partial class UserRightRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IaSiViziteaza.DAL.AccessRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Priority");

                    b.HasKey("Id");

                    b.ToTable("AccessRight");
                });

            modelBuilder.Entity("IaSiViziteaza.DAL.AttractionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("AttractionType");
                });

            modelBuilder.Entity("IaSiViziteaza.DAL.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<long>("PostalCode");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("IaSiViziteaza.DAL.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IaSiViziteaza.DAL.UserAccessRight", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("AccessRightId");

                    b.HasKey("UserId", "AccessRightId");

                    b.HasIndex("AccessRightId");

                    b.ToTable("UserAccessRights");
                });

            modelBuilder.Entity("IaSiViziteaza.DAL.UserAccessRight", b =>
                {
                    b.HasOne("IaSiViziteaza.DAL.AccessRight", "AccessRight")
                        .WithMany("UserAccessRights")
                        .HasForeignKey("AccessRightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IaSiViziteaza.DAL.User", "User")
                        .WithMany("UserAccessRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
